### ISSUE TITLE
Dependensy from 'geometry' gem

### ISSUE THREAD

**Issue by Loriowar** [bfoz/dxf-ruby#5]
I try to install 'dxf' gem in my application, but it doesn't work without gem 'geometry'. Is this a right behaviour? If it so, I think adding 'geometry' in Gemfile is a good thing.

**Comment by bfoz** [comment]
The dependency on geometry is correct, and is included in the gemspec, which is imported by the Gemfile (on line 3). Did geometry not get installed properly as a dependency? How did you install dxf?

**Comment by Loriowar** [comment]
I tried to install gem through Gemfile `gem 'dxf'`and get an error with 'geometry'. For me, installation gem from Github repository `gem 'dxf', git: 'https://github.com/bfoz/dxf-ruby'` solve a problem with 'geometry'. It's look strange. And you right, dependensy for 'geometry' described in gemspec. My appologize, looks like this is my local problem.

**Comment by bfoz** [comment]
No worries. I'm glad you got it working. Let me know if you need anything else.
