### ISSUE TITLE
Incorrect Readme and error during require 'dxf'

### ISSUE THREAD

**Issue by Loriowar** [bfoz/dxf-ruby#6]
In current version of Readme a line `require 'dxf'` doesn't work. It require `require 'valuable'` before for proper work. Maybe this issue more fit for 'sketch' gem, but I'm not sure.

**Comment by bfoz** [comment]
It sounds like the wrong version of the sketch gem was installed. The one hosted by rubygems.org won't work, you need the one that's on GitHub. The dependency should be handled correctly by bundler, but it sounds like something went wrong. Can you give me more details?

**Comment by Loriowar** [comment]
Yes, you right, I install gem directly from Github and all become well.
